export default [
  {
    id: 'cobber_1',
    date: 1519211809934,
    title: 'Superbowl',
    description: 'Match between Rams and Bengals',
    time: '1200',
    location: 'Bruin Walk',
    host: 'bill_cob',
    members: ['randall_guy', 'willy_wonka'],
  },
  {
    id: 'cobber_2',
    date: 1519211809935,
    title: 'lunch',
    description: 'cheesesteak',
    time: '2400',
    location: 'Willys',
    host: 'bill_cob',
    members: [],
  },
  {
    id: 'randall_1',
    date: 1519211809935,
    title: 'dinner',
    description: 'icecream',
    time: '1500',
    location: 'Konkers',
    host: 'randall_guy',
    members: ['bill_cob'],
  },
]
